WebApplication3/WebApplication3/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class CalcController : Controller
    {
        // GET: Calc
        public ActionResult Add(int? x, int? y)
        {
            ViewBag.Result = x + y;
            return View();
        }

        public ActionResult Mul(int? x, int? y)
        {
            ViewBag.Result = x - y;
            return View("Add");
        }

        public ActionResult Sub(int? x, int? y)
        {
            ViewBag.Result = x * y;
            return View("Add");
        }

        public ActionResult Div(double x, double y)
        {
            if (y != 0)
                ViewBag.Result = Math.Round(x / y, 2);
            else
                ViewBag.Result = 0;
            return View("Add");
        }
    }
}

WebApplication3/WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication3/WebApplication3/Views/Calc/Add.cshtml
@{
    ViewBag.Title = "Result";
}

<h2>Add</h2>
@ViewBag.Result
<br>
@Html.ActionLink("4 + 6 ", "Add", "Calc", new { x = 4, y = 6 }, null)
<br>
@Html.ActionLink("4 - 6 ", "Mul", "Calc", new { x = 4, y = 6 }, null)
<br>
@Html.ActionLink("4 * 6 ", "Sub", "Calc", new { x = 4, y = 6 }, null)
<br>
@Html.ActionLink("4 / 6 ", "Div", "Calc", new { x = 4, y = 6 }, null)